### ISSUE TITLE
Document behavior for bibliography in YAML front matter

### ISSUE THREAD

**Issue by David96** [vim-pandoc/vim-pandoc#292]
Hey,

so I usually use a format like that for my yaml frontmatter:
```
---
title: Some Title
author: me
date: 12.12.2018
toc: true
toc-own-page: true
nocite: "@*"
references:
- id: source1
  type: webpage
  URL: https://foo
  title: Some other title
- id: source2
  type: webpage
  title: Title
  URL: https://bar
---
```
That works perfectly fine using pandoc-citeproc. Now I was wanting to have some auto completion for that and found out that the bibliography plugin actually is supposed to support YAML frontmatter (which isn't documented by the way).
Obvious problem: it uses the "bibliography" key instead of "references". But even using that I can't get auto complete to work.
The problem seems to be, that the YAML isn't parsed right to start with. The b:pandoc_yaml_data dictionary is just empty for me.
A minimal test file like that:
```
---
bibliography:
  - id: test
    type: test
---
```
Gives a dictionary like that: {'id': 'test', 'type': 'test'}
So somehow the bibliography key doesn't even get added.

So how am I supposed to structure my frontmatter so it works with the YAML plugin? Or maybe it's possible to rewrite the YAML Plugin to support this style?

Thanks in advance and have a nice day :)
